// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfWaNXIR-UJ5bxvdu8DkNTP-3-Ho_3mA',
    appId: '1:926248188694:web:f74b90930495abbed56e37',
    messagingSenderId: '926248188694',
    projectId: 'neuroverse-app-8e744',
    authDomain: 'neuroverse-app-8e744.firebaseapp.com',
    storageBucket: 'neuroverse-app-8e744.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDm8guqTDvf4tnfX8vhgcIlRsSA-DJQU',
    appId: '1:926248188694:android:99faca4c0ce1abcad56e37',
    messagingSenderId: '926248188694',
    projectId: 'neuroverse-app-8e744',
    storageBucket: 'neuroverse-app-8e744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonrHYvFbe78wGAd7JNbl-eiP4NwExZn8',
    appId: '1:926248188694:ios:a491e4d83a79e95fd56e37',
    messagingSenderId: '926248188694',
    projectId: 'neuroverse-app-8e744',
    storageBucket: 'neuroverse-app-8e744.firebasestorage.app',
    iosBundleId: 'com.example.neuroverseChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonrHYvFbe78wGAd7JNbl-eiP4NwExZn8',
    appId: '1:926248188694:ios:a491e4d83a79e95fd56e37',
    messagingSenderId: '926248188694',
    projectId: 'neuroverse-app-8e744',
    storageBucket: 'neuroverse-app-8e744.firebasestorage.app',
    iosBundleId: 'com.example.neuroverseChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpfWaNXIR-UJ5bxvdu8DkNTP-3-Ho_3mA',
    appId: '1:926248188694:web:397a12ab3b21041ad56e37',
    messagingSenderId: '926248188694',
    projectId: 'neuroverse-app-8e744',
    authDomain: 'neuroverse-app-8e744.firebaseapp.com',
    storageBucket: 'neuroverse-app-8e744.firebasestorage.app',
  );
}
