name: NeuroVerse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter:
    name: Flutter Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'

      - name: Get dependencies
        run: |
          cd neuroverse_chatbot/neuroverse_chatbot
          flutter pub get

      - name: Analyze Flutter code
        run: |
          cd neuroverse_chatbot/neuroverse_chatbot
          flutter analyze

  backend:
    name: Python Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd neuroverse_chatbot/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Python files
        run: |
          cd neuroverse_chatbot/backend
          python -m compileall .
